Assignment1CarlosAlves/Assignment1CarlosAlves/Models/State.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1CarlosAlves.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public int FirstZipCode { get; set; }
        public int LastZipCode { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}

Assignment1CarlosAlves/Assignment1CarlosAlves/Controllers/StatesController.cs
using Assignment1CarlosAlves.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment1CarlosAlves.Controllers
{
    public class StatesController : Controller
    {

        // GET: States
        /// <summary>
        /// The view returns a list of all states
        /// </summary>
        /// <param name="id">The search term</param>
        /// <param name="sortBy">Integer. 0 = StateCode, 1 = stateName, 2 = first ZipCode, 3 = LastZip</param>
        /// <returns></returns>
        public ActionResult AllStates(string id, int sortBy = 0)
        {

            TechSupportEntities context = new TechSupportEntities();
            //List<State> states = context.States.OrderBy(s => s.StateName).ToList();
            List<State> states;

            switch (sortBy)
            {
                case 1:
                    {
                        //if (isDesc)
                        //    states = context.States.OrderByDescending(s => s.StateCode).ToList();
                        //else
                        states = context.States.OrderBy(s => s.StateName).ToList();
                        break;
                    }
                case 2:
                    {
                        //if (isDesc)
                        //    states = context.States.OrderByDescending(s => s.StateName).ToList();
                        //else
                        states = context.States.OrderBy(s => s.FirstZipCode).ToList();
                        break;
                    }

                case 3:
                    {
                        //if (isDesc)
                        //    states = context.States.OrderByDescending(s => s.FirstZipCode).ToList();
                        //else
                        states = context.States.OrderBy(s => s.LastZipCode).ToList();
                        break;
                    }

                case 0:
                default:
                    {
                        //if (isDesc)
                        //    states = context.States.OrderByDescending(s => s.LastZipCode).ToList();
                        //else
                        states = context.States.OrderBy(s => s.StateCode).ToList();
                        break;
                    }

            }
            //id is used as "searchTerm" parameter
            if (!string.IsNullOrWhiteSpace(id))
            {
                id = id.Trim().ToLower();
                int zipCodeLookup = 0;


                //in case id is an integer
                if (int.TryParse(id, out zipCodeLookup))
                {
                    Console.WriteLine(id);
                    states = states.Where(s =>
                               s.FirstZipCode == zipCodeLookup ||
                               s.LastZipCode == zipCodeLookup
                                ).ToList();
                }
                else // if id does not parse
                {
                    states = states.Where(s =>
                      s.StateCode.ToLower().Contains(id) ||
                      s.StateName.ToLower().Contains(id)
                      ).ToList();
                }


            }

            foreach (var state in states)
            {
                int numOfCustomers = state.Customers.Count();
            }

            return View(states);
        }

        [HttpGet]
        public ActionResult UpsertStates(string id)
        {
            //State state = new State();
            TechSupportEntities context = new TechSupportEntities();
            State state = context.States.Where(s => s.StateCode == id).FirstOrDefault();

            return View(state);
        }

        [HttpPost]
        public ActionResult UpsertStates(State newState)
        {
            TechSupportEntities context = new TechSupportEntities( );

            try
            {
                if (context.States.Where(s => s.StateCode == newState.StateCode).Count() > 0)
                {
                    var stateToSave = context.States.Where(s => s.StateCode == newState.StateCode).FirstOrDefault();
                    stateToSave.StateName = newState.StateName;
                    stateToSave.FirstZipCode = newState.FirstZipCode;
                    stateToSave.LastZipCode = newState.LastZipCode;
                }
                else{
                    context.States.Add(newState);
                }
             
                context.SaveChanges();

            }
            catch
            {
                //log the exception in the error log and send an automatic email to IT support
                //throw;
            }

            

             return RedirectToAction("AllStates");
        }
       

    }


}

Assignment1CarlosAlves/Assignment1CarlosAlves/Views/States/AddStates.cshtml
@model  Assignment1CarlosAlves.Models.State
@{
    ViewBag.Title = "Add a State";
}

<h2>Add States</h2>

@*<form action="/States/AddStates" method="post">
    <input type="text" name="StateCode" />
    <input type="text" name="StateName" />
    <input type="text" name="FirstZipCode" />
    <input type="text" name="LastZipCode" />
    <input type="submit" value="submit" />
</form>*@

@using (Html.BeginForm("AddStates", "States", FormMethod.Post))
{
    @Html.TextBoxFor(s => s.StateCode, new { @class = "form-control" } )
    @Html.TextBoxFor(s => s.StateName, new { @class = "form-control" })
    @Html.TextBoxFor(s => s.FirstZipCode, new { @class = "form-control" })
    @Html.TextBoxFor(s => s.LastZipCode, new { @class = "form-control" })

    <input type="submit" value="submit" class="btn btn-info"/>
}

Assignment1CarlosAlves/Assignment1CarlosAlves/Views/States/AllStates.cshtml
@model List<Assignment1CarlosAlves.Models.State>
@{
    ViewBag.Title = "AllStates";
}

<h2>All States Page </h2>
<button class="btn btn-primary"><a class="text-decoration-none link-light" href="/States/UpsertStates">Add new State</a></button>


<div class="row m-2">
    <div class="col-4">
        <input id="txtSearch" type="text" name="textSearch" class="form-control" placeholder="Search..." />

    </div>
    <div class="col-3">
        <input type="button" class="btn btn-primary btn-md" name="searchButton" value="Search" onclick="Sortable.Search();" />
    </div>
</div>


<table class="sortable table table-striped table-hover table-dark table-bordered">
    <thead class="table-light">
        <tr>
            <th onclick="Sortable.Sort(0)">State Code</th>
            <th onclick="Sortable.Sort(1)">State Name</th>
            <th onclick="Sortable.Sort(2)">First Zip Code </th>
            <th onclick="Sortable.Sort(3)">Last Zip Code</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var state in Model)
        {
            <tr>
                <td>@state.StateCode</td>
                <td>@state.StateName</td>
                <td>@state.FirstZipCode</td>
                <td>@state.LastZipCode</td>
                <td>
                    <button  class="btn btn-primary"><a href="/States/UpsertStates/@state.StateCode" class="text-decoration-none link-light">Edit</a></button>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>

    Sortable.baseUrl = '/States/AllStates/';
</script>







@*<script>
    function sort(sortBy) {
        let isDesc = false;

        var url_string = window.location.href;
        var url = new URL(url_string);
        var isDescUrlParam = url.searchParams.get("isDesc");
        if (isDescUrlParam == "false") {
            isDesc = true;
        }

        window.location.href = "/States/AllStates/?sortBy=" + sortBy + "&isDesc=" + isDesc;
    }

</script>*@

Assignment1CarlosAlves/Assignment1CarlosAlves/Views/States/UpsertStates.cshtml
@model  Assignment1CarlosAlves.Models.State
@{
    ViewBag.Title = "Upsert a State";
}

<h2>Add States</h2>

@*<form action="/States/AddStates" method="post">
    <input type="text" name="StateCode" />
    <input type="text" name="StateName" />
    <input type="text" name="FirstZipCode" />
    <input type="text" name="LastZipCode" />
    <input type="submit" value="submit" />
</form>*@

@using (Html.BeginForm("UpsertStates", "States", FormMethod.Post))
{
    @Html.TextBoxFor(s => s.StateCode, new { @class = "form-control" } )
    @Html.TextBoxFor(s => s.StateName, new { @class = "form-control" })
    @Html.TextBoxFor(s => s.FirstZipCode, new { @class = "form-control" })
    @Html.TextBoxFor(s => s.LastZipCode, new { @class = "form-control" })

    <input type="submit" value="submit" class="btn btn-info"/>
}