Assignment1CarlosAlves/Assignment1CarlosAlves/Models/Incident.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1CarlosAlves.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int IncidentID { get; set; }
        public int CustomerID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> TechID { get; set; }
        public System.DateTime DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Technician Technician { get; set; }

    }
}

Assignment1CarlosAlves/Assignment1CarlosAlves/Controllers/IncidentsController.cs
using Assignment1CarlosAlves.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment1CarlosAlves.Controllers
{

    public class IncidentsController : Controller
    {
        // GET: Incidents

        public ActionResult AllIncidents(string id, int sortBy=0, bool isDesc = false)
        {
            TechSupportEntities context = new TechSupportEntities();
            List<Incident> incidents;

            switch (sortBy)
            {
                case 1:
                    {
                        if (isDesc)
                            incidents = context.Incidents.OrderByDescending(i => i.Title).ToList();
                        else
                            incidents = context.Incidents.OrderBy(i => i.Title).ToList();
                        break;
                    }
                case 2:
                    {
                        if (isDesc)
                            incidents = context.Incidents.OrderByDescending(i => i.Description).ToList();
                        else
                            incidents = context.Incidents.OrderBy(i => i.Description).ToList();
                        break;
                    }

                case 3:
                    {
                        if (isDesc)
                            incidents = context.Incidents.OrderByDescending(i => i.DateOpened).ToList();
                        else
                            incidents = context.Incidents.OrderBy(i => i.DateOpened).ToList();
                        break;
                    }
                case 4:
                    {
                        if (isDesc)
                            incidents = context.Incidents.OrderByDescending(i => i.DateClosed).ToList();
                        else
                            incidents = context.Incidents.OrderBy(i => i.DateClosed).ToList();
                        break;
                    }
                case 5:
                    {
                        if (isDesc)
                            incidents = context.Incidents.OrderByDescending(i => i.ProductCode).ToList();
                        else
                            incidents = context.Incidents.OrderBy(i => i.ProductCode).ToList();
                        break;
                    }
                case 6:
                    {
                        if (isDesc)
                            incidents = context.Incidents.OrderByDescending(i => i.TechID).ToList();
                        else
                            incidents = context.Incidents.OrderBy(i => i.TechID).ToList();
                        break;
                    }


                case 0:
                default:
                    {
                        if (isDesc)
                            incidents = context.Incidents.OrderByDescending(i => i.IncidentID).ToList();
                        else
                            incidents = context.Incidents.OrderBy(i => i.IncidentID).ToList();
                    }
                    break;
            }
            if (!string.IsNullOrWhiteSpace(id))
            {
                id = id.Trim().ToLower();
                int incidentsLookUp = 0;


                //in case id is an integer
                if (int.TryParse(id, out incidentsLookUp))
                {
                    Console.WriteLine(id);
                    incidents = incidents.Where(i =>
                               i.IncidentID == incidentsLookUp
                               ).ToList();


                }
                else // if id does not parse
                {
                    incidents = incidents.Where(i =>
                     i.Title.ToLower().Contains(id) ||
                      i.Description.ToLower().Contains(id)
                     
                      ).ToList();
                }


            }

            return View(incidents);
        }


        [HttpGet]
        public ActionResult UpsertIncidents(string id)
        {
            TechSupportEntities context = new TechSupportEntities();
            Incident incident = context.Incidents.Where(i => i.IncidentID.ToString() == id).FirstOrDefault();
            List<Customer> customers = context.Customers.ToList();
            List<Product> products = context.Products.ToList();
            List<Technician> technicians = context.Technicians.ToList();

            UpsertIncidentsModel viewModel = new UpsertIncidentsModel()
            {
                Incident = incident,
                Customers = customers,
                Products = products,
                Technicians = technicians,


            };
            return View(viewModel);

        }

        [HttpPost]
        public ActionResult UpsertIncidents(UpsertIncidentsModel model)
        {
            Incident newIncident = model.Incident;
            TechSupportEntities context = new TechSupportEntities();
            try
            {
                if(context.Incidents.Where(i => i.IncidentID == newIncident.IncidentID).Count() > 0 )
                {
                    var incidentToSave = context.Incidents.Where(i => i.IncidentID == newIncident.IncidentID).FirstOrDefault();
                    incidentToSave.Title = newIncident.Title;
                    incidentToSave.Description = newIncident.Description;
                    incidentToSave.DateOpened = newIncident.DateOpened;
                    incidentToSave.DateClosed = newIncident.DateClosed;
                    incidentToSave.ProductCode = newIncident.ProductCode;
                    incidentToSave.TechID = newIncident.TechID;
                    incidentToSave.CustomerID = newIncident.CustomerID;
                    
                    
                }
                else
                {
                    context.Incidents.Add(newIncident);
                }
                context.SaveChanges();

            }
            catch (System.Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("AllIncidents");
        }

    }

   


}

Assignment1CarlosAlves/Assignment1CarlosAlves/Views/Incidents/AllIncidents.cshtml
@model List<Assignment1CarlosAlves.Models.Incident>
@{
    ViewBag.Title = "AllIncidents";
}

<h2>All Incidents Page</h2>
<button class="btn btn-primary"><a class="text-decoration-none link-light" href="/Incidents/UpsertIncidents">Add new incident</a></button>
<div class="row m-2">
    <div class="col-4">
        <input class="form-control" id="txtSearch" type="text" name="textSearch" placeholder="Search..." />
    </div>
    <div class="col-3">
        <input type="button" class="btn btn-primary btn-md" name="searchButton" value="Search" onclick="Sortable.Search();" />
    </div>
</div>

<table class="sortable table table-striped table-hover table-dark table-bordered">
    <thead class="table-light">
        <tr>
            <th onclick="sort(0)">Incident ID</th>
            <th onclick="sort(1)">Title</th>
            <th onclick="sort(2)">Desciption</th>
            <th onclick="sort(3)">Date Opened</th>
            <th onclick="sort(4)">Date Closed</th>
            <th onclick="sort(5)">Product Code</th>
            <th onclick="sort(6)">Tech ID</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var incident in Model)
        {
            <tr>
                <td>@incident.IncidentID</td>
                <td>@incident.Title</td>
                <td>@incident.Description</td>
                <td>@incident.DateOpened</td>
                <td>@incident.DateClosed</td>
                <td>@incident.ProductCode</td>
                <td>@incident.TechID</td>
                <td>
                    <button class="btn btn-primary"><a href="/Incidents/UpsertIncidents/@incident.IncidentID" class="text-decoration-none link-light">Edit</a></button>
                </td>

            </tr>
        }

    </tbody>
</table>

<script>
    Sortable.baseUrl = '/Incidents/AllIncidents/';

</script>

Assignment1CarlosAlves/Assignment1CarlosAlves/Views/Incidents/UpsertIncidents.cshtml
@model  Assignment1CarlosAlves.Models.UpsertIncidentsModel
@{
    ViewBag.Title = "Upsert Incidents";
}

<h2>UpsertIncidents</h2>


@using (Html.BeginForm("UpsertIncidents", "Incidents", FormMethod.Post))
{
    @*<div class="form-floating mb-3 ">
        @Html.TextBoxFor(gm => gm.Incident.IncidentID, new { @class = "form-control", @type = "ID", @placeholder = "Incident ID" })
        <label>Incident ID</label>

    </div>*@

    <div class="form-floating mb-3 ">
        @Html.TextBoxFor(gm => gm.Incident.Title, new { @class = "form-control", @type = "ID", @placeholder = "Incident Title" })
        <label>Incident Title</label>
    </div>
    <div class="form-floating mb-3 ">

        @Html.TextBoxFor(gm => gm.Incident.Description, new { @class = "form-control", @type = "ID", @placeholder = "Incident Description" })
        <label for="">Incident Description</label>
    </div>
    <div class="form-floating mb-3 ">
        @Html.TextBoxFor(gm => gm.Incident.DateOpened, new { @class = "form-control", @type = "ID", @placeholder = "Incident Date Opened" })
        <label for="">Incident Date Opened</label>

    </div>
    <div class="form-floating mb-3 ">
        @Html.TextBoxFor(gm => gm.Incident.DateClosed, new { @class = "form-control", @type = "ID", @placeholder = "Incident Date Closed" })
        <label class="">Incident Date Closed</label>
    </div>
    <div class="form-floating mb-3 ">
        <select name="Model.Products.PoductCode" class="form-control ">

            @foreach (var product in Model.Products)
            {
                <option class="form-control " type="ID" placeholder="Product Code" vlaue="@product.ProductCode">@product.ProductCode</option>
            }
        </select>
    </div>
    <div class="form-floating mb-3 ">
        <select name="Model.Customer.CustomerID" class="form-control ">

            @foreach (var technician in Model.Technicians)
            {
                <option class="form-control " type="ID" placeholder="Technician ID" vlaue="@technician.TechID">@technician.TechID</option>
            }
        </select>
    </div>
    @*<div class="form-floating mb-3 ">
        @foreach (var technician in Model.Technicians)
        {
            <label class="">Technician ID</label>
            <option class="form-control" type="ID" placeholder="Technician ID" vlaue="@technician.TechID"></option>
        }
        @Html.TextBoxFor(gm => gm.Technician, new { @class = "form-control", @type = "ID", @placeholder = "Technician" })
        <label class="">Technician </label>
    </div>*@
<div class="form-floating mb-3 ">
    <select name="Model.Customer.CustomerID" class="form-control ">

        @foreach (var customers in Model.Customers)
        {
            <option class="form-control " type="ID" placeholder="Customer ID" vlaue="@customers.CustomerID">@customers.CustomerID</option>
        }
    </select>
    
</div>


    <input type="submit" value="submit" class="btn btn-info" />
}